### ISSUE TITLE
Unable to get lights to be static

### ISSUE THREAD

**Issue by sondregronas** [pyhammond/retropie_wiimote_lights#2]
Controller: Nintendo Switch Pro Controller
Raspberry Pi 3 B+
Linux retropie 4.14.71-v7+ armv71 GNU/Linux

Issue: The lights keep dancing as if the controller is still syncing.
I connected the controllers using bluetoothctl as shown here: https://retropie.org.uk/docs/Wii-U-Pro-Controller/
The only thing that isn't stock is that I'm running VirtualHere passing through a bluetooth adapter (I'm using internal for this controller). I've modified /etc/profile.d/10-retropie.sh to launch VirtualHere:

```
sudo ./Downloads/vhusbdarm -b
# launch our autostart apps (if we are on the correct tty)
if [ "`tty`" = "/dev/tty1" ] && [ "$USER" = "pi" ]; then
    bash "/opt/retropie/configs/all/autostart.sh"
fi
```

Also modified /opt/retropie/configs/all/autostart.sh:
```
sudo bash -c 'echo 1 > /sys/module/bluetooth/parameters/disable_ertm'
emulationstation #auto
```
My Raspberry Pi is underclocked to 600Mhz

Thanks in advance!

**Comment by pyhammond** [comment]
Are you using a Switch Pro Controller?  Or a Wii U Pro Controller?

I've never used this software with a Switch Pro Controller.  I don't even have one to test it with, so you may be on your own with this one.

This software was originally made for the Wii U Pro Controller to connect to RetroPie.
